Finance_system/Finance_system/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('', include('micro_admin.urls')),
    path('dashboard/', include('savings.urls')),
    path('dashboard/', include('loans.urls')),
    path('finance/', include('core.urls')),
    path('admin/', admin.site.urls),

]

Finance_system/core/urls.py
from django.urls import path
from core.views import receipts_deposit, client_loan_accounts_view, get_loan_demands_view, payslip_create_view, get_group_loan_accounts, \
    get_member_loan_accounts, get_fixed_deposit_accounts_view, get_recurring_deposit_accounts_view, client_deposit_accounts_view, \
    get_fixed_deposit_paid_accounts_view, get_recurring_deposit_paid_accounts_view

urlpatterns = [
    path('receiptsdeposit/', receipts_deposit, name="receiptsdeposit"),
    path('getmemberloanaccounts/', client_loan_accounts_view,
         name="getmemberloanaccounts"),
    path('getloandemands/', get_loan_demands_view, name="getloandemands"),
    path('payslip/', payslip_create_view, name="payslip"),
    path('loanaccounts/group', get_group_loan_accounts,
         name="get_group_loan_accounts"),
    path('loanaccounts/member', get_member_loan_accounts,
         name="get_member_loan_accounts"),
    path('getmemberfixeddepositaccounts/',
         get_fixed_deposit_accounts_view, name="getmemberfixeddepositaccounts"),
    path('getmemberrecurringdepositaccounts/',
         get_recurring_deposit_accounts_view, name="getmemberrecurringdepositaccounts"),
    path('getmemberdepositaccounts/', client_deposit_accounts_view,
         name="getmemberdepositaccounts"),
    path('getmemberfixeddepositpaidaccounts/',
         get_fixed_deposit_paid_accounts_view, name="getmemberfixeddepositpaidaccounts"),
    path('getmemberrecurringdepositpaidaccounts/',
         get_recurring_deposit_paid_accounts_view, name="getmemberrecurringdepositpaidaccounts"),
]

Finance_system/micro_admin/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, Permission


GENDER_TYPES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

USER_ROLES = (
    ('BranchManager', 'BranchManager'),
    ('LoanOfficer', 'LoanOfficer')
)

CLIENT_ROLES = (
    ('FirstLeader', 'FirstLeader'),
    ('SecondLeader', 'SecondLeader'),
    ('GroupMember', 'GroupMember')
)

ACCOUNT_STATUS = (
    ('Applied', 'Applied'),
    ('Withdrawn', 'Withdrawn'),
    ('Approved', 'Approved'),
    ('Rejected', 'Rejected'),
    ('Closed', 'Closed'),
)


INTEREST_TYPES = (
    ('Flat', 'Flat'),
    ('Declining', 'Declining'),
)

RECEIPT_TYPES = (
    ('EntranceFee', 'EntranceFee'),
    ('MembershipFee', 'MembershipFee'),
    ('BookFee', 'BookFee'),
    ('LoanProcessingFee', 'LoanProcessingFee'),
    ('SavingsDeposit', 'SavingsDeposit'),
    ('FixedDeposit', 'FixedDeposit'),
    ('RecurringDeposit', 'RecurringDeposit'),
    ('AdditionalSavings', 'AdditionalSavings'),
    ('ShareCapital', 'ShareCapital'),
    ('PeenalInterest', 'PeenalInterest'),
    ('LoanDeposit', 'LoanDeposit'),
    ('Insurance', 'Insurance'),
)

FD_RD_STATUS = (
    ('Opened', 'Opened'),
    ('Paid', 'Paid'),
    ('Closed', 'Closed'),
)

PAYMENT_TYPES = (
    ('Loans', 'Loans'),
    ('TravellingAllowance', 'TravellingAllowance'),
    ('Paymentofsalary', 'Paymentofsalary'),
    ('PrintingCharges', 'PrintingCharges'),
    ('StationaryCharges', 'StationaryCharges'),
    ('OtherCharges', 'OtherCharges'),
    ('SavingsWithdrawal', 'SavingsWithdrawal'),
    ('FixedWithdrawal', 'Fixed Deposit Withdrawal'),
    ('RecurringWithdrawal', 'Recurring Deposit Withdrawal'),
)


class Branch(models.Model):
    name = models.CharField(max_length=100, unique=True)
    opening_date = models.DateField()
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    area = models.CharField(max_length=150)
    phone_number = models.BigIntegerField()
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class UserManager(BaseUserManager):

    def create_user(self, username, email, branch=None, password=None):
        if not username:
            raise ValueError('Users must have an username')

        # Save the user
        user = self.model(username=username)
        user.set_password(password)
        user.email = email
        user.branch = branch
        user.is_staff = True
        user.save()
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, email="", password=password)
        user.is_admin = True
        user.is_active = True
        user.save()
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True)
    gender = models.CharField(choices=GENDER_TYPES, max_length=10)
    branch = models.ForeignKey(
        Branch, on_delete=models.CASCADE, null=True, blank=True)
    user_roles = models.CharField(choices=USER_ROLES, max_length=20)
    date_of_birth = models.DateField(default='2000-01-01', null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    country = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    district = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    area = models.CharField(max_length=150, null=True)
    mobile = models.CharField(max_length=10, default='0', null=True)
    pincode = models.CharField(default='', max_length=10, null=True)
    user_permissions = models.ManyToManyField(
        Permission, related_name='user_permissions', blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    def __unicode__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        if self.is_active and self.is_admin:
            return True
        # return _user_has_perm(self, perm, obj)
        else:
            try:
                user_perm = self.user_permissions.get(codename=perm)
            except ObjectDoesNotExist:
                user_perm = False

            return bool(user_perm)

    class Meta:
        permissions = (
            ("branch_manager",
             "Can manage all accounts under his/her branch."),
        )


class Client(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    account_number = models.CharField(max_length=50, unique=True)
    date_of_birth = models.DateField()
    blood_group = models.CharField(max_length=10, default=True, null=True)
    gender = models.CharField(choices=GENDER_TYPES, max_length=10)
    client_role = models.CharField(choices=CLIENT_ROLES, max_length=20)
    occupation = models.CharField(max_length=200)
    annual_income = models.BigIntegerField()
    joined_date = models.DateField()
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    area = models.CharField(max_length=150)
    mobile = models.CharField(max_length=20, default=True, null=True)
    pincode = models.CharField(max_length=20, default=True, null=True)
    photo = models.ImageField(upload_to=settings.PHOTO_PATH, null=True)
    signature = models.ImageField(upload_to=settings.SIGNATURE_PATH, null=True)
    is_active = models.BooleanField(default=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default="UnAssigned", null=True)
    sharecapital_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    entrancefee_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    membershipfee_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    bookfee_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    insurance_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()


class ClientBranchTransfer(models.Model):
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, related_name='client_name')
    from_branch = models.ForeignKey(
        Branch, on_delete=models.CASCADE, related_name='from_branch')
    to_branch = models.ForeignKey(
        Branch, on_delete=models.CASCADE, related_name='to_branch')
    changed_on = models.DateTimeField(auto_now=True)
    changed_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='changed_by')

    def __str__(self):
        return self.client.first_name + '-' + 'from:' + self.from_branch.name + '-to:' + self.to_branch.name


class Group(models.Model):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="group_created_by")
    account_number = models.CharField(max_length=50, unique=True)
    activation_date = models.DateField()
    is_active = models.BooleanField(default=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    staff = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    clients = models.ManyToManyField(Client, blank=True)
    status = models.CharField(max_length=50, default="UnAssigned")

    def __unicode__(self):
        return self.name


class Centers(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created_date = models.DateField()
    is_active = models.BooleanField(default=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, blank=True)

    def __unicode__(self):
        return self.name


class GroupMeetings(models.Model):
    meeting_date = models.DateField()
    meeting_time = models.CharField(max_length=20)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.group.name + ' ' + self.meeting_date


class SavingsAccount(models.Model):
    account_no = models.CharField(max_length=50, unique=True)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, null=True, blank=True)
    group = models.ForeignKey(
        Group, on_delete=models.CASCADE, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(choices=ACCOUNT_STATUS, max_length=20)
    opening_date = models.DateField()
    min_required_balance = models.DecimalField(max_digits=5, decimal_places=2)
    savings_balance = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    annual_interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    total_deposits = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    total_withdrawals = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    fixeddeposit_amount = models.DecimalField(
        max_digits=19, decimal_places=6, default=0)
    fixeddepositperiod = models.IntegerField(null=True, blank=True)
    recurringdeposit_amount = models.DecimalField(

Finance_system/templates/client/create.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>Create Member</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-2 margin-top-set">
    <div class="panel-heading"><i class="fa fa-plus padd"></i>Create Member</div>
    <div class="panel-body pb-pad">
      <form id="createclientform" class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <!--div 1 0f form-->
        <div class="box-form">
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">First Name<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="first_name" id="first_name">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Last Name<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="last_name" id="last_name">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Gender<span>*</span></label>
            <div class="col-sm-8 mar-top-rad">
              <input type="radio" name="gender" value="M">Male &nbsp;&nbsp;
              <input type="radio" name="gender" value="F">Female
              <br/><span id="gender"></span>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Branch<span>*</span></label>
            <div class="col-sm-8">
              <select class="text-box wid-form select-box-pad" name="branch" id="branch">
                <option>Select Branch</option>
                {% for branch in branches %}
                  <option value="{{ branch.id }}">{{ branch.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Member Roles<span>*</span></label>
            <div class="col-sm-8">
              <select class="text-box wid-form select-box-pad" name="client_role" id="client_role">
                <option>Select Member Roles</option>
                {% for key, role in client_roles %}
                  <option value="{{ role }}">{{ role }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Joined Date<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="date-picker-cc" name="joined_date">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Date Of Birth<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="datepicker-dob" name="date_of_birth">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Created By<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" value="{{ user.username }}" name="created_by" id="created_by" readonly>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Account Number<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="account_number" id="account_number">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Occupation<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="occupation" id="occupation">
            </div>
          </div>
        </div>
        <!--div 1 of fomr ends above-->
        <!--div 2 of form starts below-->
        <div class="box-form">
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Blood Group</label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="blood_group" id="blood_group">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Annual Income<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="annual_income" id="annual_income">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
            <div class="col-sm-8">
              <input type="email" class="text-box wid-form" name="email" id="email">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Mobile<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="mobile" id="mobile">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Country<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="country" name="country">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">State<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="state" name="state">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">District<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="district" name="district">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Mandal<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="city" name="city">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Area<span>*</span></label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" id="area" name="area">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Pin-Code</label>
            <div class="col-sm-8">
              <input type="text" class="text-box wid-form" name="pincode" id="pincode">
            </div>
          </div>
        </div>
        <br clear="all" />
        <!--branch 2 ends above-->
        <!--btn row-->
        <div class="btns-row">
          <div class="form-group btns align-btns">
            <button class="submit-btn"><i class="fa fa-check padd"></i>Submit</button>
            <button class="cancel-btn" type="reset"><i class="fa fa-times padd"></i>Cancel</button>
          </div>
        </div>
        <!--btn row ends above-->
      </form>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
</div>
<!--wrapper ends above-->
{% endblock %}
{% block extra_js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    $('#createclientform').submit(function (e) {
      e.preventDefault();
      $("span.error").remove();
      $.post('.', $('#createclientform').serialize(), function (data) {
        if (data.error) {
          $("span.error").remove();
          $.each(data.errors, function( key, value ) {
            if (key == 'date_of_birth'){
              $('#datepicker-dob').after("<span class='error' style='height:11px;color:red;'> * " + value + "</span>");
            }
            if (key == 'joined_date'){
              $('#date-picker-cc').after("<span class='error' style='height:11px;color:red;'> * " + value + "</span>");
            }
            else{
              $('#'+key).after("<span class='error' style='height:11px;color:red;'> * " + value + "</span>");
            }
          });
        }
        else {
          alert("Member created sucessfully.");
          window.location = data.success_url;
        }
      }, "json");
    });
    $('.cancel-btn').click(function (e) {
      $("span.error").remove();
    });
  });
</script>
{% endblock extra_js %}

Finance_system/templates/client/list.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>View Members</li>
{% endblock %}
{% block stage %}
<div class="container">
  <div class="row search_list">
    <div class="col">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search branch" aria-label="Username" aria-describedby="sizing-addon2"> <span class="input-group-addon" id="sizing-addon2"><i class="fa fa-search" aria-hidden="true"></i></span>
      </div>
    </div>
    <div class="col">
      <button type="button" class="pull-right branch">Create Member</button>
    </div>
  </div>
  <div class="row list_page_view">
    <table class="table table-striped" data-tablesaw-mode="columntoggle" id="active_users">
      <thead>
        <tr>
          <th width="15%" scope="col">Member Name</th>
          <th width="15%" scope="col">Account Number</th>
          <th width="15%" scope="col">Branch Name</th>
          <th width="15%" scope="col">Group Name</th>
          <th width="15%" scope="col">Role</th>
          <th width="10%" scope="col">Status</th>
          <th width="15%" scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for client in client_list %}
        <tr>
          <td><a href="{% url 'micro_admin:clientprofile' client.id %}" style="color:#337ab7">
          {{ client.first_name|capfirst }} {{ client.last_name|capfirst }}</a></td>
          <td>{{ client.account_number }}</td>
          <td><a href="{% url 'micro_admin:branchprofile' client.branch.id %}" style="color:#337ab7">{{ client.branch.name|capfirst}}</a></td>
          <td>
            {% if client.group_set.get %}
              <a href="{% url 'micro_admin:groupprofile' client.group_set.get.id %}" style="color:#337ab7">
                {{ client.group_set.get.name|capfirst}} Group </a>
            {% else %} - {% endif %}
          </td>
          <td>{{ client.client_role }}</td>
          {% if client.is_active %}
            <td><a href="{% url 'micro_admin:deleteclient' client.id %}"><i class="fa fa-circle green pad-lt"></i></a></td>
          {% else %}
            <td><a href="{% url 'micro_admin:deleteclient' client.id %}"><i class="fa fa-circle red pad-lt"></i></a></td>
          {% endif %}
          <td class="ed">
            <a href="{% url 'micro_admin:clientprofile' client.id %}"><i class="fa fa-eye"></i></a>
            <a href="{% url 'micro_admin:editclient' client.id %}"><i class="fa fa-pencil-square-o edit-icon"></i></a>
            {% if client.is_active %}
              {% if user.is_admin or user.user_roles == "BranchManager" %}
                <a href="{% url 'micro_admin:deleteclient' client.id %}"><i class="fa fa-trash-o trash-icon"></i></a>
              {% endif %}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

Finance_system/templates/client/profile.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' client.branch.id %}">{{ client.branch.name|capfirst }} Branch</a></li>
<li>{{ client.first_name|capfirst }} Member</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="wrap-cp-div margin-top-set">
    <div class="btn-row">
      <a href="{% url 'micro_admin:editclient' client.id %}"><button><i class="fa fa-pencil-square-o padd"></i>Edit</button></a>
      {% if client.savingsaccount_set.count %}
      <a href="{% url 'savings:clientsavingsaccount' client.id %}"><button><i class="fa fa-money padd"></i>View Savings</button></a>
      {% else %}
      <a href="{% url 'savings:clientsavingsapplication' client.id %}"><button><i class="fa fa-plus padd"></i>Savings</button></a>
      {% endif %}
      <a href="{% url 'loans:clientloanapplication' client.id %}"><button><i class="fa fa-plus padd"></i>Loan</button></a>
      <a href="{% url 'loans:clientloanaccountslist' client.id %}"><button><i class="fa fa-money padd"></i>View Loans</button></a>
      <a href="{% url 'micro_admin:viewparticularclientfixeddeposits' client.id%}"><button><i class="fa fa-eye padd"></i>Fixed Deposits</button></a>
      <a href="{% url 'micro_admin:viewparticularclientrecurringdeposits' client.id%}"><button><i class="fa fa-eye padd"></i>Recurring Deposits</button></a>
      <a href="{% url 'micro_admin:updateclientprofile' client.id %}"><button><i class="fa fa-file-image-o padd"></i>Update Profile</button></a>
      {% if user.is_admin or user.user_roles == "BranchManager" %}
      <a href="{% url 'micro_admin:deleteclient' client.id %}"><button><i class="fa fa-trash-o padd"></i>Delete</button></a>
      {% endif %}
      <br clear="all" />
    </div>
    <div class="clr-div" style ="width:100%">
      <div class="img-div">
        <h3>{{ client.last_name|capfirst }} {{ client.first_name|capfirst }}</h3>
        <img src="{% if client.photo %}/{{ client.photo }}{% else %}/static/images/default_user.png{% endif %}" alt="Member Photo" /><br /><br />
        <img src="{% if client.signature %}/{{client.signature}}{% else %}/static/images/signature.png{% endif %}"  class="sig-div" style="" alt="Member Signature" />
        <br clear="all" />
      </div>
      <div class="details-div">
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 cl-md-6 col-sm-6 col-xs-7 control-label">Branch Name : </label>
          <a href="{% url 'micro_admin:branchprofile' client.branch.id %}">
          {{ client.branch.name|capfirst }} Branch
          </a>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Status : </label>
          {% if client.is_active %}
          <td><i class="fa fa-square icon-squa green padd"></i>Active</td>
          {% else %}
          <td><i class="fa fa-square icon-squa red padd"></i>InActive</td>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Joined Date : </label>
          {{ client.joined_date }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Group : </label>
          {% if client.group_set.get %}<a href="{% url 'micro_admin:groupprofile' client.group_set.get.id %}">
            {{ client.group_set.get.name|capfirst}} Group </a>
          {% else %} - {% endif %}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Account Number : </label>
          {{ client.account_number }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Member Role : </label>
          {{ client.client_role|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">State : </label>
          {{ client.state|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">District : </label>
          {{ client.district|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Mandal : </label>
          {{ client.city|capfirst }}
        </div>
        <div class="form-group" >
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Mobile : </label>
          {{ client.mobile|default:" - " }}
        </div>

        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Share Capital Amount: </label>
          {{ client.sharecapital_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Entrance Fee Amount: </label>
          {{ client.entrancefee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Membership Fee Amount: </label>
          {{ client.membershipfee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Book Fee Amount : </label>
          {{ client.bookfee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Insurance Amount : </label>
          {{ client.insurance_amount|floatformat:2 }}
        </div>
      </div>
      <br clear="all" />
    </div>
    <!--form div ends above-->
  </div>
  <!--content ends above-->
</div>
{% endblock %}